name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "*.gitignore"
      - "*.txt"
      - "*.png"
      - "*.mtx"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  testrunner:
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, thread, undefined]
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        run: apt install gcc-13 g++-13
      - name: Set toolchain
        run: |
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/gcov gcov /usr/bin/gcov-13
          update-alternatives --set gcc /usr/bin/gcc-13
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          ./build.sh -t Debug -o "-DCMAKE_CXX_FLAGS=-fsanitize=${{ matrix.sanitizer }}"
      - name: Run tests
        run: |
          build/bin/mtx2img .github/assets/fidap005.mtx out.png
          build/bin/mtx2img .github/assets/fidap005.mtx out.png -w 10
          build/bin/mtx2img .github/assets/fidap005.mtx out.png -h 20
          build/bin/mtx2img .github/assets/fidap005.mtx out.png -w 10 -h 20
          build/bin/mtx2img .github/assets/fidap005.mtx out.png -w 10 -h 20 -c kindlmann
          build/bin/mtx2img --help

  package:
    needs: testrunner
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        run: apt install gcc-13 g++-13
      - name: Set toolchain
        run: |
          update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/gcov gcov /usr/bin/gcov-13
          update-alternatives --set gcc /usr/bin/gcc-13
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: ./build.sh -t Release -i artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-ubuntu
          path: artifacts
