name: PKG

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "*.gitignore"
      - "*.txt"
      - "!CMakeLists.txt"
      - "*.png"
      - "*.mtx"
      - "*.mm"
  workflow_dispatch:

jobs:
  packager:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          ./build.sh                                  \
            -t Release                                \
            -p
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-ubuntu
          path: build/*Linux.zip
      - name: Upload source artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-source
          path: build/*Source.zip
