name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "*.gitignore"
      - "*.txt"
      - "!CMakeLists.txt"
      - "*.png"
      - "*.mtx"
      - "*.mm"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "*.gitignore"
      - "*.txt"
      - "!CMakeLists.txt"
      - "*.png"
      - "*.mtx"
      - "*.mm"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  testrunner:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, thread, undefined]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: |
          ./build.sh                                  \
            -t Debug                                  \
            -o "-DCMAKE_CXX_COMPILER=/usr/bin/g++-13" \
            -o "-DCMAKE_CXX_FLAGS=-fsanitize=${{ matrix.sanitizer }}"
      - name: Run tests
        run: |
          if ! build/bin/mtx2img --help; then
            exit 1
          fi

          if ! build/bin/mtx2img .github/assets/fidap005.mtx out.png; then
            exit 1
          fi

          if ! cat .github/assets/fidap005.mtx | build/bin/mtx2img - out.png; then
            exit 1
          fi

          if ! build/bin/mtx2img .github/assets/fidap005.mtx - > out.png; then
            exit 1
          fi

          if ! cat .github/assets/fidap005.mtx | build/bin/mtx2img - - > out.png; then
            exit 1
          fi

          if ! build/bin/mtx2img .github/assets/fidap005.mtx out.png -r 10; then
            exit 1
          fi

          for colormap in binary kindlmann viridis glasbey256 glasbey64 glasbey8; do
            for aggregation in count sum max; do
              echo "build/bin/mtx2img .github/assets/fidap005.mtx out.png -r 10 -a $aggregation -c $colormap"
              if ! build/bin/mtx2img .github/assets/fidap005.mtx out.png -r 10 -a $aggregation -c $colormap; then
                exit 1
              fi
            done
          done
